apiVersion: 1

datasources:
  - name: Stream Engine Prometheus
    uid: stream-engine-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
